name: flutter-ci

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.2"
      - name: Install dependencies
        run: flutter pub get
      - name: build runner
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: generate files
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: analyze
        run: flutter analyze
